import 'dart:io';

/// Persisted project settings written by `flutter_architect init`.
class ProjectConfig {
  const ProjectConfig({
    required this.architecture,
    required this.stateManagement,
    required this.useHive,
    required this.useGetIt,
    required this.useEquatable,
    required this.networking,
    required this.useLocalization,
    required this.useFlavors,
  });

  final String architecture;
  final String stateManagement;
  final bool useHive;
  final bool useGetIt;
  final bool useEquatable;
  final String networking;
  final bool useLocalization;
  final bool useFlavors;

  static const defaults = ProjectConfig(
    architecture: 'clean',
    stateManagement: 'bloc',
    useHive: false,
    useGetIt: true,
    useEquatable: true,
    networking: 'rest',
    useLocalization: false,
    useFlavors: false,
  );

  bool get isMvvm => architecture == 'mvvm';
  bool get isClean => architecture == 'clean';
}

class ValidationUtils {
  static const configFile = 'architect.yaml';
  static const featureRegistrationsMarker = '// <FEATURE_REGISTRATIONS>';

  /// Ensures that `flutter_architect init` has been run.
  static void ensureInitialized(String root) {
    final coreDir = Directory('$root/lib/core');
    if (!coreDir.existsSync()) {
      stdout.writeln(
          '\x1B[31mError: Architecture is not initialized in this project.\x1B[0m');
      stdout.writeln(
          'Please run \x1B[1mflutter_architect init\x1B[0m first before creating features or components.');
      exit(1);
    }
  }

  /// Saves project configuration to architect.yaml.
  static void saveConfig({
    required String root,
    required String architecture,
    required String stateManagement,
    required bool useHive,
    required bool useGetIt,
    required bool useEquatable,
    required String networking,
    bool useLocalization = false,
    bool useFlavors = false,
  }) {
    final file = File('$root/$configFile');
    file.writeAsStringSync('''
# Generated by flutter_architect — do not delete.
architecture: $architecture
state_management: $stateManagement
use_hive: $useHive
use_get_it: $useGetIt
use_equatable: $useEquatable
networking: $networking
use_localization: $useLocalization
use_flavors: $useFlavors
'''.trimLeft());
  }

  /// @Deprecated — use [saveConfig]
  static void saveArchitecture(String root, String architecture) {
    final existing = readConfig(root);
    saveConfig(
      root: root,
      architecture: architecture,
      stateManagement: existing.stateManagement,
      useHive: existing.useHive,
      useGetIt: existing.useGetIt,
      useEquatable: existing.useEquatable,
      networking: existing.networking,
      useLocalization: existing.useLocalization,
      useFlavors: existing.useFlavors,
    );
  }

  static ProjectConfig readConfig(String root) {
    final file = File('$root/$configFile');
    if (!file.existsSync()) return ProjectConfig.defaults;

    final map = <String, String>{};
    for (final line in file.readAsLinesSync()) {
      final trimmed = line.trim();
      if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
      final idx = trimmed.indexOf(':');
      if (idx <= 0) continue;
      map[trimmed.substring(0, idx).trim()] =
          trimmed.substring(idx + 1).trim();
    }

    return ProjectConfig(
      architecture: map['architecture'] ?? 'clean',
      stateManagement: map['state_management'] ?? 'bloc',
      useHive: map['use_hive'] == 'true',
      useGetIt: map['use_get_it'] != 'false',
      useEquatable: map['use_equatable'] != 'false',
      networking: map['networking'] ?? 'rest',
      useLocalization: map['use_localization'] == 'true',
      useFlavors: map['use_flavors'] == 'true',
    );
  }

  /// Reads the saved architecture type from architect.yaml.
  static String readArchitecture(String root) => readConfig(root).architecture;

  /// Appends a feature DI registration call into service_locator.dart.
  static void registerFeatureInLocator({
    required String root,
    required String pascalName,
    required String snakeName,
    required String relativeImport,
  }) {
    final file = File('$root/lib/app/di/service_locator.dart');
    if (!file.existsSync()) return;

    var content = file.readAsStringSync();
    final importLine = "import '$relativeImport';";
    final callLine = '  register${pascalName}Feature();';

    if (!content.contains(importLine)) {
      final lines = content.split('\n');
      var lastImport = -1;
      for (var i = 0; i < lines.length; i++) {
        if (lines[i].startsWith('import ')) lastImport = i;
      }
      if (lastImport >= 0) {
        lines.insert(lastImport + 1, importLine);
        content = lines.join('\n');
      }
    }

    if (!content.contains(callLine)) {
      if (content.contains(featureRegistrationsMarker)) {
        content = content.replaceFirst(
          featureRegistrationsMarker,
          '$callLine\n  $featureRegistrationsMarker',
        );
      } else {
        content = content.replaceFirst(
          RegExp(r'\}\s*$'),
          '  $callLine\n}\n',
        );
      }
    }

    file.writeAsStringSync(content);
  }
}
