abstract class RouterTemplates {
  static const String goRouter = '''import 'package:go_router/go_router.dart';
import 'package:flutter/material.dart';

final GoRouter appRouter = GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const Scaffold(
        body: Center(child: Text('Home Page')),
      ),
    ),
  ],
);
''';

  static const String autoRoute = '''import 'package:auto_route/auto_route.dart';
// import 'app_router.gr.dart'; // Generated by auto_route_generator

@AutoRouterConfig(replaceInRouteName: 'Page,Route')
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    // AutoRoute(page: HomeRoute.page, initial: true),
  ];
}
''';
}
